# Site settings
title: Versatile Spirit Ran Wei's Blog
subtitle: Ran Wei's Blog 
email: versatile.spirit.info@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website! 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wendyran.github.io" # the base hostname & protocol for your site
twitter_username: wendyranstat
github_username:  wendyran

# Build settings
markdown: kramdown
