# Site settings
title: Wendy Ran Wei
subtitle: ML Engineer & Book Author
description: Wendy Ran Wei is an ML Engineer specializing in search, recommendation, and personalization systems, and the author of Advanced Retrieval-Augmented Generation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wendyran.github.io" # the base hostname & protocol for your site
twitter_username: wendyranwei
github_username:  wendyran

# Build settings
markdown: kramdown
